/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpg.generator;

import java.util.Random;
import javax.swing.JComboBox;
import javax.swing.JLabel;



/**
 *
 * @author Carl Slatter
 */
public class GUIINFO extends javax.swing.JFrame {

    /**
     * Creates new form GUIRPG
     */
   
    
    public GUIINFO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("RPG CHARACTER GENERATOR");

        jLabel2.setText("Race");

        jLabel3.setText("Gender");

        jLabel4.setText("Age");

        jLabel5.setText("Alignment");

        jLabel6.setText("Class");

        jLabel7.setText("Profession");

        jLabel8.setText("Proficiences");

        jButton3.setText("Random");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Random");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Random");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Random");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Random");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Random");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton2.setText("Randomize All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Randomize Me");

        jLabel10.setText("Randomize Me");

        jLabel11.setText("Randomize Me");

        jLabel12.setText("Randomize Me");

        jLabel13.setText("Randomize Me");

        jLabel14.setText("Randomize Me");

        jLabel15.setText("Randomize Me");

        jButton1.setText("Random");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenu5.setText("Open");
        jMenu1.add(jMenu5);

        jMenu4.setText("Save");
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Stats");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton3)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton4)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton5)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton6)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton7)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("lblRace");
        jLabel3.getAccessibleContext().setAccessibleName("lblGender");
        jLabel4.getAccessibleContext().setAccessibleName("lblAge");
        jLabel5.getAccessibleContext().setAccessibleName("lblAlignment");
        jLabel6.getAccessibleContext().setAccessibleName("lblClass");
        jLabel7.getAccessibleContext().setAccessibleName("lblProfession");
        jLabel8.getAccessibleContext().setAccessibleName("lblProficiences");
        jButton3.getAccessibleContext().setAccessibleName("btnrandomGender");
        jButton4.getAccessibleContext().setAccessibleName("btnrandomAge");
        jButton5.getAccessibleContext().setAccessibleName("btnrandomAlignment");
        jButton6.getAccessibleContext().setAccessibleName("btnrandomClass");
        jButton7.getAccessibleContext().setAccessibleName("btnrandomProfession");
        jButton8.getAccessibleContext().setAccessibleName("btnrandomProficiences");
        jButton2.getAccessibleContext().setAccessibleName("btnradnomAll");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The arrays are initialised, given content and are confined to their respective button.
     * The button also triggers an event in which the label text near the button changes
     * to random content from the array based on a random number generator.
     */
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    String[] genderarray = new String[3];
    
    genderarray[0] = "Male";
    genderarray[1] = "Female";
    genderarray[2] = "Agender";
    
         
    jLabel10.setText(genderarray[GenderGenerator()]);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * 
     * This is the event for triggering all the boxes to change, 
     * it uses the same code as the others but due to some limitations I found,
     * this way the best way for now, can be improved given time.
     */
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
    String[] racearray = new String[8];
    String[] Alignmentarray = new String[9];
    String[] Classarray = new String[11];
    String[] Professionarray = new String[7];
    String[] Proficiencesarray = new String[6];
    String[] genderarray = new String[3];
      
    racearray[0] = "Elf";
    racearray[1] = "Human";
    racearray[2] = "Dwarf"; 
    racearray[3] = "Orc"; 
    racearray[4] = "Goblin"; 
    racearray[5] = "Hylian"; 
    racearray[6] = "Argonian"; 
    racearray[7] = "Khajiit";
    
    genderarray[0] = "Male";
    genderarray[1] = "Female";
    genderarray[2] = "Agender";
    
    Alignmentarray[0] = "Lawful Good";
    Alignmentarray[1] = "Neutral Good";
    Alignmentarray[2] = "Chaotic Good"; 
    Alignmentarray[3] = "Lawful Neutral"; 
    Alignmentarray[4] = "True Neutral"; 
    Alignmentarray[5] = "Chaotic Neutral"; 
    Alignmentarray[6] = "Lawful Evil"; 
    Alignmentarray[7] = "Neutral Evil";
    Alignmentarray[8] = "Chaotic Evil";
    
    Classarray[0] = "Barbarian";
    Classarray[1] = "Bard";
    Classarray[2] = "Cleric"; 
    Classarray[3] = "Druid"; 
    Classarray[4] = "Fighter"; 
    Classarray[5] = "Monk"; 
    Classarray[6] = "Paladin"; 
    Classarray[7] = "Ranger";
    Classarray[8] = "Rouge";
    Classarray[9] = "Sorcerer";  
    Classarray[10] = "Wizard";
    
    Professionarray[0] = "Blacksmith";
    Professionarray[1] = "Botanist";
    Professionarray[2] = "Mechanic"; 
    Professionarray[3] = "Highwayman"; 
    Professionarray[4] = "Pit Fighter"; 
    Professionarray[5] = "Miner"; 
    Professionarray[6] = "Assasin";
    
    Proficiencesarray[0] = "Agile";
    Proficiencesarray[1] = "Stealthy";
    Proficiencesarray[2] = "Strong"; 
    Proficiencesarray[3] = "Defender"; 
    Proficiencesarray[4] = "Healthy"; 
    Proficiencesarray[5] = "Skilled"; 
    
    Random rnd = new Random();  
    int randomint = rnd.nextInt(100);
    String randomstring = String.valueOf(randomint);
    
    
    jLabel10.setText(genderarray[GenderGenerator()]);
    jLabel9.setText(racearray[RaceGenerator()]);
    jLabel12.setText(Alignmentarray[AlignmentGenerator()]);
    jLabel13.setText(Classarray[ClassGenerator()]);
    jLabel14.setText(Professionarray[ProfessionGenerator()]);
    jLabel15.setText(Proficiencesarray[ProficiencesGenerator()]);
    jLabel11.setText(randomstring);
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Random rnd = new Random();  
    int randomint = rnd.nextInt(100);
    String randomstring = String.valueOf(randomint);
    jLabel11.setText(randomstring);
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
     String[] Alignmentarray = new String[9];
    
    Alignmentarray[0] = "Lawful Good";
    Alignmentarray[1] = "Neutral Good";
    Alignmentarray[2] = "Chaotic Good"; 
    Alignmentarray[3] = "Lawful Neutral"; 
    Alignmentarray[4] = "True Neutral"; 
    Alignmentarray[5] = "Chaotic Neutral"; 
    Alignmentarray[6] = "Lawful Evil"; 
    Alignmentarray[7] = "Neutral Evil";
    Alignmentarray[8] = "Chaotic Evil";    
    
    
    jLabel12.setText(Alignmentarray[AlignmentGenerator()]);   
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   
    String[] Classarray = new String[11];
    
    Classarray[0] = "Barbarian";
    Classarray[1] = "Bard";
    Classarray[2] = "Cleric"; 
    Classarray[3] = "Druid"; 
    Classarray[4] = "Fighter"; 
    Classarray[5] = "Monk"; 
    Classarray[6] = "Paladin"; 
    Classarray[7] = "Ranger";
    Classarray[8] = "Rouge";
    Classarray[9] = "Sorcerer";  
    Classarray[10] = "Wizard";   
    
    
    jLabel13.setText(Classarray[ClassGenerator()]);   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String[] Professionarray = new String[7];
    
    Professionarray[0] = "Blacksmith";
    Professionarray[1] = "Botanist";
    Professionarray[2] = "Mechanic"; 
    Professionarray[3] = "Highwayman"; 
    Professionarray[4] = "Pit Fighter"; 
    Professionarray[5] = "Miner"; 
    Professionarray[6] = "Assasin"; 

    jLabel14.setText(Professionarray[ProfessionGenerator()]);    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    String[] Proficiencesarray = new String[6];
    
    Proficiencesarray[0] = "Agile";
    Proficiencesarray[1] = "Stealthy";
    Proficiencesarray[2] = "Strong"; 
    Proficiencesarray[3] = "Defender"; 
    Proficiencesarray[4] = "Healthy"; 
    Proficiencesarray[5] = "Skilled"; 
    
    jLabel15.setText(Proficiencesarray[ProficiencesGenerator()]);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String[] racearray = new String[8];
    
    racearray[0] = "Elf";
    racearray[1] = "Human";
    racearray[2] = "Dwarf"; 
    racearray[3] = "Orc"; 
    racearray[4] = "Goblin"; 
    racearray[5] = "Hylian"; 
    racearray[6] = "Argonian"; 
    racearray[7] = "Khajiit";    
    
    
    jLabel9.setText(racearray[RaceGenerator()]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIINFO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new GUIINFO().setVisible(true);
            }
        });
    }
    
    /**
     * These are the number generators for each array, 
     * due to each array being different sizes, 
     * I couldn't just use one, again, can be improved given time.
     */
    
    
    
    public int RaceGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(8);
     return randomint;
    }
    
    public int GenderGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(3);
     return randomint;
    }
    
     
    public int AlignmentGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(9);
     return randomint;
    }
     
    public int ClassGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(7);
     return randomint;
    }
      
    public int ProfessionGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(7);
     return randomint;
    }
       
    public int ProficiencesGenerator()
    {
     Random rnd = new Random();  
     int randomint = rnd.nextInt(6);
     return randomint;
    }
   


   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
